config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cities#index'
  resources :cities, only: %i[index show] do
    resources :restaurants, only: [:show]
    resources :hotels, only: [:show]
    resources :clubs, only: [:show]
  end

  resources :restaurants, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hotel, optional: true
  belongs_to :club, optional: true
  belongs_to :restaurant, optional: true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :clubs
  has_many :hotels
  has_many :restaurants
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :city
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :city
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :city
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @restaurant = @city.restaurants
    @restaurants = Restaurant.where(city_id: @city)
    @hotels = Hotel.where(city_id: @city)
    @clubs = Club.where(city_id: @city)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :find_city
  # before_action :set_restaurant, only: [:show]

  def index
    @restaurants = @city.restaurants
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  # def find_city
  #   @city = City.find(params[:id])
  # end

  # def set_restaurant
  #   @restaurant = @city.restaurants.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/cities/index.html.erb
<div class="container">
  <h1>IZIRES</h1>
  <ul>
  <% @cities.each do |city| %>
    <div class='city_card my-3'><h2><%= link_to city.name, city_path(city.id) %></h2></div>
  <% end %>
  </ul>
</div>

app/views/cities/show.html.erb
<h1><%= @city.name %></h1>

<div class="row">
  <div class="col-4">
    <h2>Restaurants</h2>

    <% @restaurants.each do |restaurant| %>
      <h3><%= link_to restaurant.name, restaurant %></h3>
    <% end %>
  </div>

  <div class="col-4">
    <h2>Hotels</h2>

    <% @hotels.each do |hotel| %>
      <h3><%= hotel.name %></h3>
    <% end %>
  </div>

  <div class="col-4">
    <h2>Bars</h2>

    <% @clubs.each do |club| %>
      <h3><%= club.name %></h3>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Izires</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/show.html.erb
<div class="container">
  <%= @restaurant.id %>
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
</div>